# Generated by Django 3.0.6 on 2020-06-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField()),
                ('Question', models.TextField(max_length=1000)),
                ('Answer', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('pic', models.ImageField(upload_to='wedding/footer_image')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=20)),
                ('color_class', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='testimonials_for_wedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=20)),
                ('caption', models.TextField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='wedding/image_testimonial_for_wedding')),
            ],
        ),
        migrations.CreateModel(
            name='wedding_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('Address', models.TextField(max_length=100)),
                ('Address2', models.TextField(default='', max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=10)),
                ('zipcode', models.IntegerField()),
                ('make', models.CharField(default='', max_length=40)),
                ('makeup', models.CharField(default='', max_length=40)),
                ('date1', models.CharField(default='', max_length=40)),
                ('date2', models.CharField(default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='wedding_coustomer_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(default='', upload_to='wedding/wed_coustemer_slider')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='wedding_main_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default=' ', max_length=100)),
                ('caption2', models.CharField(default=' ', max_length=100)),
                ('image', models.ImageField(default=' ', help_text='Size: 1920x570', upload_to='wedding/wedding_main_slider')),
                ('Camra', models.ImageField(default=' ', upload_to='wedding/wedding_man_slider_pics')),
                ('name_of_camra', models.CharField(default=' ', max_length=30)),
                ('camra_details', models.TextField(default=' ', max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wedding_photo_shoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='wedding/wed_shoot')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=3000)),
                ('camra', models.ImageField(default=' ', upload_to='wedding/wed_shoot/camra')),
                ('nameof_camra', models.CharField(default=' ', max_length=30)),
                ('detail_of_camra', models.TextField(default=' ', max_length=4000)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='wedding_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=200)),
            ],
        ),
    ]
