# Generated by Django 3.0.6 on 2020-06-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials_for_wedding',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonials_for_wedding',
            name='post',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonials_for_wedding',
            name='caption',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
