# Generated by Django 3.0.6 on 2020-06-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20200603_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials_for_wedding',
            name='pic',
            field=models.ImageField(default='', upload_to='wedding/image_testimonial_for_wedding'),
        ),
    ]
