# Generated by Django 3.0.6 on 2020-06-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_testimonials_for_wedding_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='vediolink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=300)),
                ('desc', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
