# Generated by Django 3.0.6 on 2020-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about_us_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('emailem', models.EmailField(max_length=20)),
                ('phone', models.IntegerField()),
                ('role', models.CharField(default='', max_length=40)),
                ('image', models.ImageField(default='', upload_to='pre_wedding/About_us')),
                ('work_experiance', models.TextField(default='', max_length=3000)),
                ('content_for_website', models.TextField(default='None', max_length=10000)),
                ('logo', models.ImageField(default='None', upload_to='pre_wedding/About_us_logo')),
                ('maplink', models.URLField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='', upload_to='pre_wedding/About_us_logo')),
            ],
        ),
        migrations.CreateModel(
            name='pre_wedding_coustomer_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(default='', upload_to='pre_wedding/pre_wed_coustemer_slider')),
                ('phone', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='pre_wedding_main_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default=' ', max_length=100)),
                ('caption2', models.CharField(default=' ', max_length=1000)),
                ('image', models.ImageField(help_text='Size: 1920x570', upload_to='pre_wedding/pre_wedding_main_slider')),
                ('Camra', models.ImageField(default=' ', upload_to='wedding/wedding_man_slider_pics')),
                ('name_of_camra', models.CharField(default=' ', max_length=30)),
                ('camra_details', models.TextField(default=' ', max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pre_Wedding_photo_shoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='pre_wedding/pre_wed_shoot')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=3000)),
                ('camra', models.ImageField(default=' ', upload_to='pre_wedding/pre_wed_shoot/camra')),
                ('nameof_camra', models.CharField(default=' ', max_length=30)),
                ('detail_of_camra', models.TextField(default=' ', max_length=4000)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pre_wedding_reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=20)),
                ('comment', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='pre_weding_booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('address1', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=10)),
                ('zipcode', models.IntegerField()),
                ('make', models.CharField(default='', max_length=40)),
                ('makeup', models.CharField(default='', max_length=40)),
                ('date11', models.CharField(default='', max_length=40)),
                ('date21', models.CharField(default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='testimonials_for_pre_wedding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=20)),
                ('caption', models.TextField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='pre_wedding/pre_wed_image_testimonial_for_wedding')),
            ],
        ),
    ]
