# Generated by Django 3.0.6 on 2020-06-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prewedding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workdemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkv', models.URLField(max_length=400)),
                ('descv', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
