# Generated by Django 3.0.6 on 2020-06-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prewedding', '0002_workdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials_for_pre_wedding',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonials_for_pre_wedding',
            name='pic',
            field=models.ImageField(default='', upload_to='pre_wedding/image_testimonial_for_wedding'),
        ),
        migrations.AddField(
            model_name='testimonials_for_pre_wedding',
            name='post',
            field=models.CharField(default='', max_length=200),
        ),
    ]
