# Generated by Django 3.0.6 on 2020-06-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prewedding', '0003_auto_20200604_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials_for_pre_wedding',
            name='caption',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
